### ISSUE TITLE
obj23dtiles -i objTo3d-tiles/bin/barrel/barrel.obj  

### ISSUE THREAD

**Issue by Frankling** [PrincessGod/objTo3d-tiles#30]
module.js:487
    throw err;
    ^

Error: Cannot find module './obj2B3dm'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/objTo3d-tiles/lib/obj23dtiles.js:5:16)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/objTo3d-tiles/bin/obj23dtiles.js:8:19)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)

#####################################################
运行出现这个问题，这个模块该从什么地方下载安装呢

**Comment by ilmy** [comment]
同问

**Comment by leonardokidd** [comment]
Change the ./lib/obj2b3dm to ./lib/obj2B3dm solved the issue for me.
